---
title: "WISE Science Retreat"
author: "Danielle Quinn"
date: "Monday, November 16, 2015"
output: html_document
runtime: shiny
---

## Length-Frequency ##

**Question 1: How big are the fish that are being caught?**

**Question 2: How does gear type influence the size of fish that are caught?**

```{r, echo=FALSE, warnings=FALSE}
library(ggplot2)
mylengths<-data.frame(length=rep(rnorm(400, 5, 19),2), type=c(rep(c('Trawl','Seine','Angler','Weir'), 100), rep('All',400)))

mylengths$length<-abs(mylengths$length)

inputPanel(selectInput("gear_type", label="Gear Type:",
              choices=c('All', 'Trawl', 'Seine', 'Angler', 'Weir'), selected='All'))

renderPlot(
  {
    ggplot(mylengths[mylengths$type==input$gear_type,])+
      geom_histogram(aes(x=length), fill='grey50', col='black')+
      theme_bw(15)+ylab("Count")+xlab("Length (cm)")+
      ggtitle(paste("Length of Fish Captured (",input$gear_type,")",sep=''))
  })
```


**To Do:**

- Figure out how to make the y axis consistent. Possibly using the table function with appropriate binning of lengths. Is there an easier way?

- Set plot dimensions.


## Growth Rates ##

```{r, echo=FALSE}
library(reshape2)
mygrowth<-data.frame(id=c(1:20),startlength=abs(rnorm(20,4,2)))
mygrowth$endlength<-mygrowth$startlength+mygrowth$startlength*0.04
mygrowth2<-melt(mygrowth, id.vars="id")
mygrowth$growthrate<-mygrowth$endlength-mygrowth$startlength/365

inputPanel(selectInput("plot_type", label="Plot:",
              choices=c('a', 'b'), selected='b'))

renderPlot(
  {
    ggplot(mygrowth2)+
      geom_point(aes(x=variable, y=value))+
      geom_line(aes(x=variable, y=value, group=id))+
      theme_bw(15)+ylab("Length (cm)")+xlab("Days Since First Measurement")
  })

renderPlot(
  {
    ggplot(mygrowth)+
      geom_boxplot(aes(x=1,y=growthrate))+
      theme_bw(15)
  })
```